language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8" MPICH_CXX="g++-4.8" MPICH_CC="gcc-4.8"; fi
  - sudo apt-get install -y mpich2 libmpich2-dev
  - sudo apt-get install -y libfftw3-dev libnetcdf-dev
  - sudo apt-get install -y python-numpy python-netcdf python-scipy
  - sudo apt-get install -y python-matplotlib
script:
  - ./.travis_script.sh
