language: cpp
compiler: gcc
matrix:
  include:
  - env: CONFIGURE_OPTIONS='--enable-openmp'
  - env: CONFIGURE_OPTIONS='--enable-debug'
  allow_failures:
  - env: CONFIGURE_OPTIONS='' MPICH_CC=clang MPICH_CXX=clang++
    compiler: clang
  - env: CONFIGURE_OPTIONS='--enable-openmp' MPICH_CC=clang MPICH_CXX=clang++
    compiler: clang
  - env: CONFIGURE_OPTIONS='--enable-debug' MPICH_CC=clang MPICH_CXX=clang++
    compiler: clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8" MPICH_CXX="g++-4.8" MPICH_CC="gcc-4.8"; fi
  - sudo apt-get install -y mpich2 libmpich2-dev
  - sudo apt-get install -y libfftw3-dev libnetcdf-dev
  - sudo apt-get install -y python-numpy python-netcdf4 python-scipy
  - sudo apt-get install -y python-matplotlib
  - sudo apt-get install -y python3-numpy python3-netcdf4 python3-scipy
  - sudo apt-get install -y python3-matplotlib
script:
  - ./.travis_script.sh
