os: linux
dist: xenial
language: cpp
compiler: gcc

git:
  depth: 3

# Define some aliases for some repeated config variables
# Note &<name> creates a reference that we can refer to later using
# *<name>, see https://en.wikipedia.org/wiki/YAML#Syntax
_aliases:
  - &petsc_vars
    - PETSC_DIR=/usr/lib/petscdir/3.6.2/x86_64-linux-gnu-real
    - PETSC_ARCH=""
    - SLEPC_DIR=/usr/lib/slepcdir/3.6.1/x86_64-linux-gnu-real
    - SLEPC_ARCH=""
  - &codecov_secure
    - secure: "M5U3I81hzK41Kw7KB+DpEMxP/sgkWkFI4uiRZQDMDFRlhcitsJQQ/YGeBt3a0vo153m2P2PmmeKUl/lTo5WS5SfAVFI8BkcyBjpxZQXV3OD8ru7JsMgVc5pGwl2dvR8Qz02gUIbrIpAlf3YDnNVb6F1C9ofDaCnZU3GUTLH5Fy5z5Z8OpuTaLmTVMMnT2ZEcRawHbmlVhIB/9PUQUa+fM7iC+dtszFxZ2ma5LOHxPS2sGpRCKE5Sae1/xAFWjo4oO0ZqYu5JFvKdb+/2yWKTg/1aTyxCdqAzLg4ldzDlX759zXgtWn+k3TLiVyQ+gsvF8QZkh4BKvl/w2KZ20vRP3blzmxvdsSH+ZP92MZIIK9EkNPGd+UJJd5Hu+zwecEFyfO8bXB9l00kzUsVx+lo7VHbANuNO3b5a6FRiihTCgk+dfOxxrow/fci+lQ9BkmJg0680SIj2e6UM/P9lFgfQLH3IoacN1PtkyqnpJqdHUdbWmpqMtmitmQhXHjnJ+wDb5+i9b1fy5yEsB64rjgF9PBr1/Nos1XD4oGWAknXmQTgWhNyy6f+e0wBNcSUd5nrReLTOAscyXYpcTqONp1W999JSFQEH+YTwBfXytdkWaAGAFEhaaAXQ2jCwHO7jl/TODPfSeZgXkQiT5jgg63i5tlPB4Xn0MTSCX74bYIi16Tk="    
  - &coverage_vars
    - SCRIPT_FLAGS='-cu'
    - PIP_PACKAGES='gcovr'

addons:
  apt:
    packages: &standard_packages
    - libfftw3-dev
    - libnetcdf-dev
    - libnetcdf-c++4-dev
    - netcdf-bin
    - hdf5-tools
    - python3
    - python3-h5py
    - python3-pip
    - python3-pytest
    - python3-numpy
    - python3-scipy
    - lcov
    - libhdf5-mpi-dev
    - openmpi-bin
    - libopenmpi-dev
    - libpetsc3.6.2-dev
    - libslepc3.6.1-dev
    - liblapack-dev
    - libparpack2-dev

cache:
  directories:
  - $HOME/local

jobs:
  fast_finish: true
  include:
  - name: "Optimised"
    env: &default_env
      - CONFIGURE_OPTIONS="--enable-shared --enable-checks=no --enable-optimize=3 --disable-signal --disable-track --disable-backtrace --with-petsc --with-slepc --with-sundials=$HOME/local"
      - SCRIPT_FLAGS='-uim'
      - PIP_PACKAGES='cython~=0.29 netcdf4~=1.5 sympy~=1.5'
      - LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
      - *petsc_vars
  - name: "GCC 7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - *standard_packages
    env:
      - *default_env
      - CONFIGURE_OPTIONS="--enable-sigfpe --enable-debug --with-petsc --with-slepc --with-sundials=$HOME/local CXXFLAGS=-g0"
      - CC=gcc-7 CXX=g++-7
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - name: "Shared library + Python"
    env:
      - *default_env
      - CONFIGURE_OPTIONS="--enable-shared --with-petsc --with-slepc --with-sundials=$HOME/local"
      - SCRIPT_FLAGS="-uim -t python"
  - name: "4to5 test"
    env:
      - *default_env
      - CONFIGURE_OPTIONS="--enable-shared --with-petsc --with-slepc --with-sundials=$HOME/local"
      - SCRIPT_FLAGS="-uim5t python"
  - name: "OpenMP"
    env:
      - *default_env
      - CONFIGURE_OPTIONS="--enable-shared --enable-openmp --with-petsc --with-slepc --with-sundials=$HOME/local"
      - OMP_NUM_THREADS=2
  - name: "3D Metric"
    env:
      - *default_env
      - CONFIGURE_OPTIONS="--enable-metric-3d --enable-shared --enable-openmp"
      - SCRIPT_FLAGS="-uim -t python -t shared"
#CMAKE
  - name: "CMake"
    env:
      - *default_env
      - OMP_NUM_THREADS=2
      - PYTHONPATH="${TRAVIS_BUILD_DIR}/tools/pylib:${TRAVIS_BUILD_DIR}/build/tools/pylib:$PYTHONPATH"
    script:
      - ./.build_sundials_for_travis.sh
      - mkdir build && cd build
      - cmake .. -DUSE_PETSC=ON -DUSE_SLEPC=ON -DUSE_SUNDIALS=ON -DSUNDIALS_ROOT="$HOME/local" -DENABLE_OPENMP=ON -DBUILD_SHARED_LIBS=ON
      - cmake --build . --target build-check -j 2
      - cmake --build . --target check
#CLANG
  - name: "Clang"
    env:
      - *default_env
      - CONFIGURE_OPTIONS="--enable-shared --enable-debug --with-petsc --with-slepc --with-sundials=$HOME/local"
      - MPICH_CC=clang MPICH_CXX=clang++
      - OMPI_CC=clang OMPI_CXX=clang++
    compiler: clang
#COVERAGE
  - name: "Coverage (full)"
    if: branch IN (master, next) OR commit_message =~ /build coverage/
    addons:
      apt:
        packages:
          - *standard_packages
          - jq
    env:
      - CONFIGURE_OPTIONS="--enable-code-coverage --enable-shared --enable-debug --enable-track --enable-checks=3 --with-petsc --with-lapack --with-slepc --enable-openmp --with-sundials=$HOME/local"
      - OMP_NUM_THREADS=2
      - LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
      - *coverage_vars
      - *petsc_vars
      - *codecov_secure
  - name: "Coverage (minimal)"
    if: branch IN (master, next) OR commit_message =~ /build coverage/
    addons:
      apt:
        packages:
          - *standard_packages
          - jq
    env:
      - CONFIGURE_OPTIONS="--enable-code-coverage --enable-shared --disable-debug --disable-checks"
      - *coverage_vars
      - *codecov_secure

  - stage: Finalise Coverage
    if: branch IN (master, next) OR commit_message =~ /build coverage/
    addons:
      apt:
        packages:
          - *standard_packages
          - jq
    env:
      - *coverage_vars
      - *codecov_secure
    script: wget -q -O ~/codacy-coverage-reporter-assembly-latest.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.5/codacy-coverage-reporter-4.0.5-assembly.jar ; java -jar ~/codacy-coverage-reporter-assembly-latest.jar final

before_install:
  ##################################################
  # Job specific setup
  ##################################################
  # The following eval is the way to force CC/CXX to desired values as travis forces values
  # for these in the pre-before_install stage, see https://docs.travis-ci.com/user/languages/cpp/#C11-C%2B%2B11-(and-Beyond)-and-Toolchain-Versioning
  - eval "${MATRIX_EVAL}"
  - echo "${CC} $(${CC} --version)"
  ##################################################
  # Install remaining python3 packages using pip
  ##################################################
  - source .pip_install_for_travis.sh ${PIP_PACKAGES}

script:
  # Configure, compile and run test_suite
  - "./.travis_script.sh ${SCRIPT_FLAGS}"

notifications:
  # Send a notification to the BOUT++ Slack team
  slack:
    secure: keU2ApI8C1M5q1700iNWmhzAQN5iJCciuP6V1lAjVBE8C2C/8mnYK3Pe83wok97buvvfVs5Qjq1+MSYSTCEw+dEye7p+1aBH7qg8C2Jyw+ugFe+6vmijag3v8DqkkzUGyF4X7+ei7YfV4G7u7YAlq/BqzD9e0SA7aASZJ3CF42f4lHKwTe0mnJfqOb8MwCBbSytzdj/iQH/O/pch03CjVObv2A88gaC5YMwYpeTAMMNGZThHsJHcVFCAz4MbvOApKSnykbRbE4AooF6lhUnAg/V40+ews5Q0NhYSLoOcQohLljLTMKAL2oRS34WdunnAEdIighLztFBNI/CKO8uaFBsWZcT2E4qRrajYTnuhCop5fUtk2lsrwUV36WFKLswa74KaSjXgpjvrV1MIidkRztPhYwcJdk9yvEroZ67C4GPBLZ6jZF/nUU9l2toPNkzGkxhDB9r9MIU2l0PJ2d3wRCcZ59jZ/Gr1Bminsyr20AU1JO5tsiO+6UI+7hxXQXtz/1knlmiZ/pXj/3Sp8+KQ/Z0MUeayC0CROFoZt/HekA6z34YcmeN/nMcXCnO7HTZ+bw7LasaIsrHbQ3PYPn8Be2f1hj4sPBnPpruN5FFYYc29c/ek8FET9LLD8a3v1V8P2udy/y5RnDqFskx+OfqKL8tSJk/zSbK/JPCTnx1rfsU=
